language: ruby
rvm:
- 2.3.3
script:
- bin/rake db:create db:migrate RAILS_ENV=test
- bin/rake
deploy:
- provider: codedeploy
  access_key_id:
    AWS_KEY_ID:
      secure: K3iT4msxmqf7EVHYTia1an1qvK1RHHwWsJhOzP/IhsYoz8eHbwPsU4c1eRz2mChuquyVY6gNjlavsmy+WC/W7UQKR23dFbbo3/A6rl8NRDA8ZgUANuaTIpNmxYLWYaZyCpL8g9domuBQ8zB87zn/WIRDQGB20oEMQPvRoWTk2nl6Xy3BlDEbU/1uOhxF+x9TBUxJWfLXY1bpuwvu4D450Mx2Cj0S+Ij6xo1C9LJq+Tv8MAdcbUYz4h9HO60xi7qr7VJEsK7WO9n8Hu8I4fRabABb17Qv/d5h4iwre5e/QAKI7Byv5FCXGmONtUX8+3YmROtPm6pV+3g4cY385oovNlh+fhIh///VddyIbPUALkkGPE6Qc3b7zBl3mX5NKxlbkvAEfGg8h4pXaGzFLNmr8IL1sT8Gh5J2x/IYrLXYlNQAhBnIkeV1xb3w7LDGxSeU7kdqovLCZJ6NwuwfgiBr0siyvEpNi7OHg2dwlVNC/6DeUo340q3U7x0wFufZdqJ1UXjzse++RnVRFs5w534hBw4t9tNf7x7C01vuNQm1s94jotZ8j0tEcCjKbY0+SWiX6QzQUuHMDMKvJ45vNxOc2/pQcmKmo6um4vynM1/BAyXUi7PVTFmVImFmG7qqFHsesFG2lrl9MScXSfpGWvbl9KHYu+vqaEI2H4JfjGVzqBk=
  secret_access_key:
    AWS_SECRET_ACCESS_KEY:
      secure: hsPVnZH9KtFAwJLorAYLkjVf8uCBsECSPuPdXJbNNrxheKu9hbnmq3rlYBwSqENBWsKExSwLo8P/58JSMXzBjhjdHY2yQVJtH2GyNeXg7IkviGHTWfGjd9xN3dmhUHubHNbA0Q6EKDjdgzicPMkozsW8O0c2W27D+7WhL4RnnNzXkCIqDVFVwVM3IkVlCRjetiVLYCEUClMIgiUB6UpubuBUG5thacvNIS63/Jty0Q7KCszmVIgevPgZKK7AmxCTPr/mac2A828lVeWP3B5b7RznmDaG4QcwG2aw9pLOcDaDM5YhkPcxU7krhwsYtPqyoiaDrvD2b3LOE+jvwy5dTHsGtbT6+fz0M9XExacXPA2CXlyRScvkhcHW/LY1URgyLtOvVXIoYEy8jkEkh2Uf7Bn37h0KyGIYjN0iTNMfbe6jiF88E+uyY2ngsDb/566kjYmWn0kuZbr0lDVTWAHeV9A6UcPbeaMYL6tHHiM+F8dHoajblb80pL2nxkn4djaW0kNbHGBHBypx59PCUZzf4dKLs84GTalIvUvIyrXBCQSc7UNvtbfaMeRIjnwHpVr777fkB/7Yixj+sTsIL07lC4Kq0grFbMPogvm0IByES164bChB/lCPlwrNeEtn0Dq2o8qgsy/YvSiHthH4+VUSuCHXdQvspqI+SfqBlmYkowM=
  bucket: psc-bookings
  key: PscBookings.zip
  application: psc-staging
  deployment_group: psc-staging-group
  
