version: 0.0
os: linux
files:
  - source: source
    destination: /apps/psc-bookings
hooks:
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 3600
