version: 0.0
os: linux
files:
  - source: /
    destination: /app/psc-bookings
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 180
      runas: deploy
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 180
      runas: deploy
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 3600
      runas: root
