version: '2'
services:
  db:
    image: postgres:9.6
    volumes:
      - data-volume:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "32500:3000"
    depends_on:
      - db
volumes:
  data-volume:
